#!/bin/sh

MKFILE=Makefile
CROSS=
CC=gcc
CHECK_DEPS=" \
    make \
    sed \
    xxd \
    pexports \
    md5sum \
" \

CC_CHECK=0
CHECK_CC=" \
    mingw32-$CC \
    i686-w64-mingw32-$CC \
" \

for i in $CHECK_DEPS; do
    echo -n "checking for $i... "
    if [ -z $(which $i 2>/dev/null) ]; then
        echo not found
        exit 1
    fi
    echo $(which $i)
done
if [ ! -z $1 ]; then
    MKFILE=$1
fi
if [ x`uname | sed "s/_.*//"` == xMINGW32 ]; then
    echo "  MSYSTEM=$MSYSTEM"
    CC_CHECK=1

fi
if [ x`uname` == xLinux ]; then
    echo "  Linux cross build"
    CC_CHECK=2
fi
if [ $CC_CHECK -eq 0 ]; then
    echo Unsupported cross build
    exit 1
fi
for i in $CHECK_CC; do
    if [ ! -z $(which $i 2>/dev/null) ]; then
        CROSS=`which $i | sed "s/.*\///;s/$CC.*//"`
        echo "  CROSS=$CROSS"
        echo "  CC=$CC"
    fi
done
if [ ! -f ../src/Makefile.in ]; then
    echo Missing ../src/Makefile.in
    exit 1
fi
cat ../src/Makefile.in | sed "s/^\(CROSS=\).*/\1$CROSS/" > $MKFILE
if [ $CC_CHECK -eq 2 ]; then
    sed -i -e "/.*MSYSTEM\"\ !=\ \"MINGW32\".*/d" $MKFILE
    sed -i -e "s/^\(TOOLS=\)wglinfo.exe.*/\1/" $MKFILE
fi
if [ -z $(which wcc386 2>/dev/null) ]; then
    echo -- DOS32 OVL not supported --
    sed -i -e "/.*make\ \-C\ .*ovl/d" $MKFILE
fi
if [ -z $(which i686-pc-msdosdjgpp-gcc 2>/dev/null) ]; then
    echo -- DJGPP DXE not supported --
    sed -i -e "/.*make\ \-C\ .*dxe/d" $MKFILE
fi
echo "conf_wrapper: creating $MKFILE"

