#!/bin/sh

TOP=.
GIT=`echo $@ | sed "s/\-git=\(.*\)/\1/;s/\ .*//"`
if [ -z $GIT ]; then GIT=.; else shift; fi;
ARG=$@; if [ -z $ARG ]; then ARG=HEAD; fi
REV=`cd $GIT; git rev-parse --short $ARG | sed "s/\(.*\)/\1\-/"`
EMUS=$(basename $(dirname `find $TOP/include -name whpx.h`))
CRYP=$(grep HASH_ALG $TOP/qapi/crypto.json | sed "s/.*\:\ //;s/.*\(HASH_[A-Z]*\).*/\1/")
MODS=$(cat $TOP/target/i386/meson.build | tail -n 2 | head -n 1 | \
    sed "s/.*:\ //;s/\}//")
if [ -z $REV ] || [ -z $EMUS ] || [ -z $MODS ]; then exit 1; fi
[ ! -z $CRYP ]  && sed -i -e "s/HASH_ALGO/$CRYP/" \
    $TOP/hw/mesa/mesagl_pfn.h
expr "$(grep base_init\) $TOP/include/qom/object.h)" : "\(.*\*klass,\ void\ \)" >/dev/null && \
    sed -i -e "s/\*klass,\ const\ void/\*klass,\ void/;s/\"system\(\/address\-\)/\"exec\1/" \
    $(grep -rl \*klass,\ const\ void $TOP/hw/{3dfx,mesa})
sed -i -e "s/\"sys.*\//\"$EMUS\//" \
    $(grep -rl \"sys.*\/ $TOP/hw/{3dfx,mesa})
sed -i -e "s/i386.*_ss/$MODS/" \
    $TOP/hw/{3dfx,mesa}/meson.build

VLC=$(find $TOP -maxdepth 2 -name vl.c)
SRC=" \
    $TOP/hw/3dfx/g2xfuncs.h \
    $TOP/hw/mesa/mglfuncs.h \
    $VLC \
" \

echo $REV
sed -i -e "s/\(rev_\[\).*\].*/\1\]\ =\ \"$REV\"/" $SRC
grep "rev_\[" $SRC | sed "s/\(rev_\[\).*\].*/\1\]\ =\ \"$REV\"/"
